### PR TITLE
Card member to material ui card

### PR DESCRIPTION
**Pull request by larbikhounti**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 164

## Type of change

Please delete options that are not relevant.
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x ] browser
- [x ] console

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by imabp** [comment]
Please remove, unused variables from your files, and send PR.

**Comment by larbikhounti** [comment]
Alright i will

**Comment by larbikhounti** [comment]
> Please remove, unused variables from your files, and update PR.

check it now

**Comment by imabp** [comment]
Build still failing. @larbikhounti

**Comment by larbikhounti** [comment]
> Build still failing. @larbikhounti 

Well my friend i don't know why but its working locally soo good luck

**Comment by imabp** [comment]
## Still unused variable 

@larbikhounti When build is failing, that means, there is literally issue with your code.  
Please note if their is any issue with env variables. Deploy will be cancelled.  


image

**Review by imabp — COMMENTED** [review]
Netlify is still sad :(

**Comment by larbikhounti** [comment]
> Netlify is still sad :( 🙄😂😂😂

lol  still trying to make her/him happy

**Comment by imabp** [comment]
Al the best, raise new PR. once u done

**Pull request closed without merging**
