### PR TITLE
team card to material ui card :smile:

### PR DESCRIPTION
**Pull request by larbikhounti**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # holder.jsx

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x ] browser
- [x ] console

# Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by larbikhounti** [comment]
i can die now peacefully haha 
tag this pull with  **hacktoberfest**

**Comment by imabp** [comment]
Man I cannot merge this. See why ? 
Please I request to not just contribute for the sake of hacktoberfest, but for the sake of Open Source Community. 

Scroll

**Comment by imabp** [comment]
See the Chakra UI
image

**Comment by larbikhounti** [comment]
I tried to hard to make it work anyway i was so proud of my self. Thanks for the west of time

**Pull request closed without merging**
