### PR TITLE
White Menu Icon

### PR DESCRIPTION
**Pull request by SingingApple**
# Description

Added SVG hamburger menu icon for the dark mode of the website and changed the corresponding code in navbar renderer.

Fixes # 66

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested Locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Souvikns** [comment]
@SingingApple actually are migrating to material-ui, and are using material-icons rather than SVG.

**Comment by SingingApple** [comment]
@Souvikns alright, I'll replace SVG icon with material-icons. 👌

**Comment by Souvikns** [comment]
No, If you check the development branch you will see that all icons are built like Components, [check here](https://material-ui.com/components/material-icons/), so to change the color we just need to pass a `color prop`.

**Comment by SingingApple** [comment]
@Souvikns but I've been instructed to make all the changes related to dark mode in dark-mode branch and this branch uses SVGs.

**Comment by SingingApple** [comment]
@Souvikns I've made the required changes, Please review.

**Comment by imabp** [comment]
I can understand brother your hardwork @SingingApple , but we are planning to launch dark mode in v3 now, as most of the part is on hold for dark mode. I am really sorry for that. But please, you can suggest new features for website, at development branch .. except dark mode

**Pull request closed without merging**
